version: '3'
services:
  grafana:
    restart: always
    image: grafana/grafana:6.2.2
    ports:
      - 3000:3000
    volumes:
      - /var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - influx
  influxdb:
    restart: always
    image: influxdb:1.7.6
    ports:
      - 4006:8086
    volumes:
      - /var/lib/influxdb
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: "false"
      INFLUXDB_USER: user
      INFLUXDB_USER_PASSWORD: pass
      INFLUXDB_DB: boot
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: secret
    networks:
      - influx

networks:
  influx:
    driver: overlay